### ISSUE TITLE
add awnings

### ISSUE THREAD

**Issue by blizzou** [andreasnuesslein/hass_teleco_daisy#25]
hi,

can you please add awnings ? 

I can list them with discovery.py : 
```
DaisyDevice "store central " (deviceType: 22, deviceModel: 21)
  {'commandAction': 'OPEN_STOP_CLOSE', 'commandCode': 'OPEN', 'commandParam': 'OPEN', 'deviceIndex': 0, 'idDevicetypeCommandModel': 63, 'idInstallationDeviceCommand': 485844, 'lowlevelCommand': 'CH5'}
  {'commandAction': 'OPEN_STOP_CLOSE', 'commandCode': 'STOP', 'commandParam': 'STOP', 'deviceIndex': 0, 'idDevicetypeCommandModel': 64, 'idInstallationDeviceCommand': 485845, 'lowlevelCommand': 'CH7'}
  {'commandAction': 'OPEN_STOP_CLOSE', 'commandCode': 'CLOSE', 'commandParam': 'CLOSE', 'deviceIndex': 0, 'idDevicetypeCommandModel': 65, 'idInstallationDeviceCommand': 485846, 'lowlevelCommand': 'CH8'}

DaisyDevice "store de droite" (deviceType: 22, deviceModel: 21)
  {'commandAction': 'OPEN_STOP_CLOSE', 'commandCode': 'OPEN', 'commandParam': 'OPEN', 'deviceIndex': 0, 'idDevicetypeCommandModel': 63, 'idInstallationDeviceCommand': 485847, 'lowlevelCommand': 'CH5'}
  {'commandAction': 'OPEN_STOP_CLOSE', 'commandCode': 'STOP', 'commandParam': 'STOP', 'deviceIndex': 0, 'idDevicetypeCommandModel': 64, 'idInstallationDeviceCommand': 485848, 'lowlevelCommand': 'CH7'}
  {'commandAction': 'OPEN_STOP_CLOSE', 'commandCode': 'CLOSE', 'commandParam': 'CLOSE', 'deviceIndex': 0, 'idDevicetypeCommandModel': 65, 'idInstallationDeviceCommand': 485849, 'lowlevelCommand': 'CH8'}
```

**Comment by Steve00815** [comment]
@andreasnuesslein 
Hi!
Sinne the last update, i can't find my 3 Covers anymore.
The integration now just Shows/finds the blades and the led perimer of my Pergola.
The 3 (side)Covers and the Group Container all the Covers vanished!
I already reeinstalled the integration but had no luck. 
How to fix it?

**Comment by andreasnuesslein** [comment]
@Steve00815  can you do this: https://github.com/andreasnuesslein/py-teleco-daisy?tab=readme-ov-file#a-quick-glance-at-your-setup

and provide the information like @blizzou

**Comment by andreasnuesslein** [comment]
@blizzou can you describe what you have there? awnings,blinds,cover? see: https://developers.home-assistant.io/docs/core/entity/cover/#device-classes

**Comment by blizzou** [comment]
@andreasnuesslein CoverDeviceClass.AWNING

@Steve00815 @andreasnuesslein it works fine with v0.1.9

**Comment by andreasnuesslein** [comment]
@blizzou  check v0.1.12

**Comment by blizzou** [comment]
@andreasnuesslein i tried v0.1.12, now awnings are back, but I cannot control them. So maybe right class would be in fact CoverDeviceClass.SHADE sorry

**Comment by andreasnuesslein** [comment]
> [@andreasnuesslein](https://github.com/andreasnuesslein) i tried v0.1.12, now awnings are back, but I cannot control them. So maybe right class would be in fact CoverDeviceClass.SHADE sorry

the actual type shouldnt change too much. what is it, in fact?  and how exactly is it not working?  

when you open the entity here: http:// .... /config/entities    does it work there?

**Comment by Steve00815** [comment]
Same here!

The screen-control-buttons are grayed out in HA App.
![Image](https://github.com/user-attachments/assets/3e25c684-17c8-4626-8ca6-85c2c349d8f8)


Using Webbrowser the entity shows an error '!". The error-description is saying, that the entity is not longer provided by integration.
![Image](https://github.com/user-attachments/assets/ff9fb082-8b32-441f-80c3-12a3fa11f90d)

**Comment by blizzou** [comment]
> > [@andreasnuesslein](https://github.com/andreasnuesslein) i tried v0.1.12, now awnings are back, but I cannot control them. So maybe right class would be in fact CoverDeviceClass.SHADE sorry
> 
> the actual type shouldnt change too much. what is it, in fact? and how exactly is it not working?
> 
> when you open the entity here: http:// .... /config/entities does it work there?

So the devices show up in entities but when I click on it ha says "this entity is not available"

No doesnt work in /config/entities thus

It "works" on my dashboard because I still use old devices that worked with v0.1.9, but ha says "Failed to execute action cover/close_cover. 'DaisyAwningCover' object has no attribute 'position' " when I click up / down or stop. But physically it still move :)

**Comment by Steve00815** [comment]
@andreasnuesslein 
Sorry, didn't read your last comment yet. As i am not familiar with python and do not have a rooted phone I am not able to provide info using discover.py. is it somehow possible to run the script directly in HA using terminal?

**Comment by andreasnuesslein** [comment]
i know this might be a bit frustrating, but could you please remove the integration and re-add it and see which devices come and if they work then?

also: these awnings you have, are they supposed to support positioning? what do they have in the official app? open,close,stop,,  right?

**Comment by Steve00815** [comment]
@andreasnuesslein :
So I deleted the integration, restartet my raspi with HA, reinstalled the integration, added username and passwort. After that, 6 Devices and 6 entites (1 entity per device) where found:
Blades,
Led perimeter,
Screen 1,
Screen 2,
Screen 3 and
Screnn 1/2/3.
Blades and led are controllable.
The screens still are not controllable. The error is "entity not available"

![Image](https://github.com/user-attachments/assets/c9db5261-edfe-4e65-bc86-8755754eb688)

![Image](https://github.com/user-attachments/assets/3772fd54-095f-4203-a508-28edcecfd8b4)

Now I cannot even add the entities to dashboard. Bevor reinstalling the integration I was able to do so but the Buttons where grayed out!


Original Apps:
In the original App G-connect (Gibus) or daisy teleco i just have 3 options to controll the screens: open, close, stop. So yes, the screens do not have a positioning Option!

![Image](https://github.com/user-attachments/assets/ed5a5030-c051-49f7-9934-d86559fd80d7)

**Comment by andreasnuesslein** [comment]
hi guys, please check again with v0.12.1

**Comment by Steve00815** [comment]
I installed the update to v. 0.1.12.1, restartet the system, but still not working!

![Image](https://github.com/user-attachments/assets/aad3f1cb-3115-44a2-b151-8a9f5e4d7899)
![Image](https://github.com/user-attachments/assets/169299fb-c8c2-475f-961e-250cc0b366ac)

Do i need to delete integration first?

**Comment by blizzou** [comment]
@andreasnuesslein same issues as @Steve00815, same covers.

Can you add back to DaisyAwningCover : 
```python
| CoverEntityFeature.SET_POSITION
```

**Comment by andreasnuesslein** [comment]
@blizzou but you can't set_position, right?  what would that actually do?

**Comment by blizzou** [comment]
@andreasnuesslein true idk why but was working in v0.1.9 : 

```python
if isinstance(cover, DaisyAwningsCover):
            self._attr_device_class = CoverDeviceClass.AWNING
            self._attr_supported_features = (
                CoverEntityFeature.OPEN
                | CoverEntityFeature.CLOSE
                | CoverEntityFeature.SET_POSITION
                | CoverEntityFeature.STOP
            )
```

**Comment by Steve00815** [comment]
@blizzou 
In which py-file can I find the lines you quotet?
Custom_components\hass_teleco_daisy\cover.py???
Did you edit the file and tried, if your solution solves the problem?

**Comment by blizzou** [comment]
@Steve00815 yes I tried and as thought by @andreasnuesslein it does not work.

Back in v0.1.9 which was working fine, there was no specific case for deviceType: 22, deviceModel: 21 in py-teleco-daisy.

So something was working fine for our covers without ids matching back in v0.1.8 teleco-daisy.

**Comment by Steve00815** [comment]
Hmm, strange!
I just had a Look into my custom components directory. I recognized, that i have two folders with teleco integration there:
'hass_teleco_daisy' (includes e. g. file teleco-daisy.py, dated 30. March 25) and
'teleco_daisy' (dated 16th oct. 2025).
In both directory i can find an file 'cover.py'. Other files are also placed in both directories. Might this cause the malefunction?

**Comment by andreasnuesslein** [comment]
@Steve00815 at the risk of stating the obvious: have you removed all traces of it and reinstalled via HACS?


@blizzou you seem to be debugging it quite well already, maybe you can find the problem by tweaking the `cover.py` a bit more?

**Comment by Steve00815** [comment]
@andreasnuesslein 
So i once more deleted the Integration via menu and manuelly deleted the folders 'teleco_daisy' and 'hass_teleco_daisy' in 'custom_componants', restarted HA and reinstalled the integration via HACS.
**Result: still not working!**

![Image](https://github.com/user-attachments/assets/fbd5a288-691e-4358-a219-0faf27662267)

In custom_conponent i only can find the folder 'teleco_daisy'. 'hass_teleco_daisy' does not seem to be part of the integration anymore. 
Here is the content of the fordert 'teleco_daisy':

![Image](https://github.com/user-attachments/assets/2f8c81fe-3cb4-4465-b744-cb2af47a70ac)

So the file teleco-daisy.py e. g. is not part of that Installation? Isn't the file nessesary to run the integration?

**Comment by blizzou** [comment]
@andreasnuesslein @Steve00815  I think both issues are same : https://github.com/andreasnuesslein/py-teleco-daisy/issues/11

**Comment by blizzou** [comment]
@andreasnuesslein @Steve00815 this works for me, replace in [cover.py](https://github.com/user-attachments/files/22989699/cover.py) : 

```python
    @property
    def current_cover_position(self) -> int | None:
        return self._cover.position

    @property
    def current_cover_tilt_position(self) -> int | None:
        return self._cover.position
``` 

with this : 

```python
    @property
    def current_cover_position(self):
        """Return the current position of the cover."""
        if self._cover is None:
            return None
        if hasattr(self._cover, 'position'):
            return self._cover.position
        return None

    @property
    def current_cover_tilt_position(self):
        """Return the current tilt position of the cover."""
        if self._cover is None:
            return None
        if hasattr(self._cover, 'tilt_position'):
            return self._cover.tilt_position
        return None
```

**Comment by Steve00815** [comment]
@andreasnuesslein @blizzou 
Also works for me! Thank you!!!

**Comment by andreasnuesslein** [comment]
@blizzou thanks man. i would have not guessed that. what a f*** 

i'll deploy a fresh version in a bit

**Comment by andreasnuesslein** [comment]
folks, please check [v0.1.12.2](https://github.com/andreasnuesslein/hass_teleco_daisy/tree/v0.1.12.2)

**Comment by Steve00815** [comment]
@andreasnuesslein 
V.0.1.12.2 works perfect for me!
Thank you!!!
